### ISSUE TITLE
unable to reach BINANCE (wss://stream.binance.com:9443/ws)

### ISSUE THREAD

**Issue by vertin2** [Tucsky/aggr#281]
unable to reach BINANCE (wss://stream.binance.com:9443/ws)

I have been getting this error for a few weeks now. Any fix?

**Comment by Tucsky** [comment]
probably mean that Binance is blocking your ip, vpn should fix it

**Comment by mchrostowski** [comment]
I turned off all 4 of the Binance streams and am still seeing this error, though only on startup so it can be ignored without issue. Would be nice to not see any error.

Binance is definitely blocking IPs.

**Comment by Tucsky** [comment]
Ok so I stopped showing the popup right away when the client fail to connect with the exchange, now only the little red notice at the bottom left corner of the screen. A less intrusive solution to inform user he might not get the full data..

I cannot do much about the ip blocking issue tho, if you disable binance AND binance futures completely across the app there is no reason it is still showing 🤷🏼‍♂️ 

But if it persist, try 
- reanable binance & binance futures in the settings
- then in the search window make sure it targets all panes 
- and see if there is a any "binance" or "binance_futures" markets in there

I hope it help but feel free to reopen that issue if it doesn't :)
